using System;
using System.Reflection;
using Kitware.mummy.Runtime;

namespace Kitware.VTK;

/// <summary>
///    vtkSMPMergePolyDataHelper
/// </summary>
/// <remarks>
///    Utility class for merging poly data in parallel
/// This class is designed as a utility class to help merging of poly data
/// generated by filters that generate multiple polydata outputs and the associated
/// locators. It requires that the filter uses vtkSMPMergePoints which creates
/// a number of necessary data structures.
/// </remarks>
public class vtkSMPMergePolyDataHelper : WrappedObject
{
	/// <summary>
	/// Automatically generated type registration mechanics.
	/// </summary>
	public new const string MRFullTypeName = "Kitware.VTK.vtkSMPMergePolyDataHelper";

	/// <summary>
	/// Automatically generated type registration mechanics.
	/// </summary>
	public new static readonly string MRClassNameKey;

	/// <summary>
	/// Automatically generated type registration mechanics.
	/// </summary>
	static vtkSMPMergePolyDataHelper()
	{
		MRClassNameKey = "class vtkSMPMergePolyDataHelper";
		Methods.RegisterType(Assembly.GetExecutingAssembly(), MRClassNameKey, Type.GetType("Kitware.VTK.vtkSMPMergePolyDataHelper"));
	}

	/// <summary>
	/// Automatically generated constructor - called from generated code.
	/// DO NOT call directly.
	/// </summary>
	public vtkSMPMergePolyDataHelper(IntPtr rawCppThis, bool callDisposalMethod, bool strong)
		: base(rawCppThis, callDisposalMethod, strong)
	{
	}

	/// <summary>
	/// Automatically generated protected Dispose method - called from
	/// public Dispose or the C# destructor. DO NOT call directly.
	/// </summary>
	protected override void Dispose(bool disposing)
	{
		base.Dispose(disposing);
	}
}
