version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: GitVersionTask
    versions:
    - "> 5.5.0, < 6"
  - dependency-name: System.Reactive
    versions:
    - ">= 5.a, < 6"
  - dependency-name: NLog
    versions:
    - 4.7.7
    - 4.7.8
