name: Commit
on: 
  push:
  pull_request:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true  
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build solution
      run: dotnet build -c Release
    - name: Fetch nuget packages
      run: |
        mkdir -p nuget
        copy src\NLogViewer\bin\Release\*.nupkg nuget\
        copy src\NLogViewer\bin\Release\*.snupkg nuget\
    - name: Upload nuget packages as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet
        path: nuget
        if-no-files-found: error